### ISSUE TITLE
add code for login page in Tkinter

### ISSUE THREAD

**Issue by yasminehh19** [yasminehh19/python-tkinter-app1#6]
make a login form using Tkinter

**Comment by MeetoazBhardwaj** [comment]
### **"Not necessary. The Party Planning Committee is all over it.The Office" - Michael's Birthday [S02E19]**


![cats coding](https://media.giphy.com/media/ule4vhcY1xEKQ/giphy.gif)

**Comment by yasminehh19** [comment]
looks like meow tired or coding isnt it :v
